### ISSUE TITLE
Property features not sent to Zoopla

### ISSUE THREAD

**Issue by therealmyth** [ActivateMedia/heathgate#40]
For reference: 

Dear Fred,
I hope that you are well.
When our properties upload to Zoopla and Onthemarket.com they do not show with the bullet points as shown below.
Is there a way that this format can be uploaded to these sites so that all our properties show with property features?
 
Property features
·         6 Bedrooms
·         2 Reception Rooms
·         3 Bathrooms
·         House
·         Period
·         Semi-Detached
·         Garden
·         Balcony
·         Terrace
·         Roof Terrace
Property description
 
A characterful 5/6 bedroom semi-detached family house with a west facing rear garden and terrace, situated at the favoured end of this sought after enclave with a private footpath for the sole use of residents. This wonderful home offers 2,350 sq ft of bright accommodation over three floors. There is a spacious entrance hall with period fireplace, reception room, dining room, kitchen/breakfast room, principal bedroom with en-suite shower room, leading out onto a terrace with magnificent views, four further bedrooms (one with its own balcony), sixth bedroom/study, family bathroom, utility room and guest cloakroom. Located 0.3 miles to Golders Green bus and Underground station and 1.1 miles from Hampstead Village, as well as many fashionable shops, restaurants, and many highly regarded local schools, including King Alfred, St Anthony's Girls and Clowns Nursery.

Thanks,
 
Viv

**Comment by therealmyth** [comment]
@Vivharris , As discussed, I had a look at the issue with the export plugin issue with the features export. The problem was that they were getting ignored because of a glitch in a function of the plugin. This has now been fixed and export properly: https://www.zoopla.co.uk/to-rent/details/45576441

If you want I can go through and re-submit all the properties tomorrow to get all the features exported. 

Fred

**Comment by Vivharris** [comment]
Thanks that would be great x

Vivienne Harris

Office: 020 7435 3344
Mobile: 07976 737 172

HEATHGATE
105 Heath Street, Hampstead, London, NW3 6SS
Fax: 020 7433 3344   Website: www.heathgate.com<http://www.heathgate.com>

On 15 Nov 2017, at 02:51, therealmyth <notifications@github.com<mailto:notifications@github.com>> wrote:


@Vivharris<https://github.com/vivharris> , As discussed, I had a look at the issue with the export plugin issue with the features export. The problem was that they were getting ignored because of a glitch in a function of the plugin. This has now been fixed and export properly: https://www.zoopla.co.uk/to-rent/details/45576441

If you want I can go through and re-submit all the properties tomorrow to get all the features exported.

Fred

**Comment by therealmyth** [comment]
This has been done

Fred
